-- LJ AI V15.9 additive production migration. Run once in Supabase SQL Editor.
begin;
update public.profiles set plan='BASIC' where upper(coalesce(plan,''))='PREMIUM_OLD';
update public.profiles set plan='PREMIUM' where upper(coalesce(plan,'')) in ('PREMIUM_PLUS','PRO');
create table if not exists public.lj_subscriptions(user_id uuid primary key references auth.users(id) on delete cascade,plan_key text not null default 'FREE' check(plan_key in('FREE','BASIC','PREMIUM','VIP','ADMIN')),billing_period text not null default 'MONTHLY' check(billing_period in('MONTHLY','3_MONTHS','YEARLY','DAILY')),status text not null default 'free',stripe_customer_id text,stripe_subscription_id text,current_period_start timestamptz,current_period_end timestamptz,updated_at timestamptz not null default now());
create unique index if not exists lj_subscription_stripe_idx on public.lj_subscriptions(stripe_subscription_id) where stripe_subscription_id is not null;
create table if not exists public.billing_webhook_events(event_id text primary key,event_type text not null,processed_at timestamptz not null default now());
create table if not exists public.lj_usage_cycles(user_id uuid not null references auth.users(id) on delete cascade,plan_key text not null,billing_period text not null,cycle_start timestamptz not null,cycle_end timestamptz not null,text_limit integer,image_limit integer,voice_seconds_limit integer,text_used integer not null default 0,image_used integer not null default 0,voice_seconds_used integer not null default 0,refills_total integer not null default 0,refills_used integer not null default 0,refill_on_request boolean not null default false,updated_at timestamptz not null default now(),primary key(user_id,cycle_start));
create table if not exists public.lj_usage_refill_events(id bigint generated always as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,cycle_start timestamptz not null,refill_number integer not null,used_at timestamptz not null default now());
create table if not exists public.lj_user_preferences(user_id uuid primary key references auth.users(id) on delete cascade,values jsonb not null default '{}',revision bigint not null default 1,updated_at timestamptz not null default now());
create table if not exists public.lj_conversations(id text primary key,user_id uuid not null references auth.users(id) on delete cascade,title text not null default 'New conversation',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.lj_conversation_messages(id text primary key,conversation_id text not null references public.lj_conversations(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,role text not null check(role in('user','assistant')),content text not null,images jsonb not null default '[]',source_device_id text,created_at timestamptz not null default now());
create table if not exists public.lj_voice_sessions(id text primary key,user_id uuid not null references auth.users(id) on delete cascade,conversation_id text,active_device_id text not null,active_platform text not null check(active_platform in('WINDOWS','ANDROID')),status text not null check(status in('ACTIVE','HANDOVER_REQUESTED','ENDED')),handover_target text,auto_handover boolean not null default false,transcript_tail jsonb not null default '[]',last_voice_state text not null default 'IDLE',lease_token_hash text not null,lease_expires_at timestamptz not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());

-- Keep reruns additive when an earlier V15.9 draft already created these tables.
alter table public.lj_subscriptions add column if not exists billing_period text not null default 'MONTHLY';
alter table public.lj_subscriptions add column if not exists stripe_customer_id text;
alter table public.lj_subscriptions add column if not exists stripe_subscription_id text;
alter table public.lj_subscriptions add column if not exists current_period_start timestamptz;
alter table public.lj_subscriptions add column if not exists current_period_end timestamptz;
alter table public.lj_usage_cycles add column if not exists refills_total integer not null default 0;
alter table public.lj_usage_cycles add column if not exists refills_used integer not null default 0;
alter table public.lj_usage_cycles add column if not exists refill_on_request boolean not null default false;
alter table public.lj_usage_cycles add column if not exists voice_seconds_limit integer;
alter table public.lj_usage_cycles add column if not exists voice_seconds_used integer not null default 0;

create or replace function public.ensure_lj_usage_cycle(p_user_id uuid) returns public.lj_usage_cycles language plpgsql security definer set search_path=public as $$
declare s public.lj_subscriptions%rowtype;r text;p text:='FREE';b text:='DAILY';cs timestamptz;ce timestamptz;tl int:=25;il int:=3;vl int:=0;rf int:=0;rq boolean:=false;c public.lj_usage_cycles%rowtype;
begin
 select upper(coalesce(role,'USER')) into r from public.profiles where id=p_user_id;
 if r='ADMIN' then p:='ADMIN';b:='YEARLY';cs:=date_trunc('year',now());ce:=cs+interval '1 year';tl:=null;il:=null;vl:=null;
 else select * into s from public.lj_subscriptions where user_id=p_user_id and status in('active','trialing') and coalesce(current_period_end,now()+interval '1 day')>now();
  if found then p:=s.plan_key;b:=s.billing_period;cs:=coalesce(s.current_period_start,now());ce:=coalesce(s.current_period_end,now()+case b when '3_MONTHS' then interval '3 months' when 'YEARLY' then interval '1 year' else interval '1 month' end);
   if p='BASIC' then tl:=case b when '3_MONTHS' then 4500 when 'YEARLY' then 18250 else 1500 end;il:=case b when '3_MONTHS' then 180 when 'YEARLY' then 730 else 60 end;vl:=case b when '3_MONTHS' then 16200 when 'YEARLY' then 74100 else 5400 end;rf:=case when b='YEARLY' then 1 else 0 end;
   elsif p='PREMIUM' then tl:=case b when '3_MONTHS' then 9000 when 'YEARLY' then 36500 else 3000 end;il:=case b when '3_MONTHS' then 450 when 'YEARLY' then 1825 else 150 end;vl:=case b when '3_MONTHS' then 108000 when 'YEARLY' then 219000 else 18000 end;rf:=case when b='YEARLY' then 2 else 0 end;
   elsif p='VIP' then tl:=case b when '3_MONTHS' then 9000 when 'YEARLY' then 36500 else 3000 end;il:=case b when '3_MONTHS' then 900 when 'YEARLY' then 3650 else 300 end;vl:=case b when '3_MONTHS' then 108000 when 'YEARLY' then 438000 else 36000 end;rf:=case when b='YEARLY' then 5 else 0 end;rq:=b='3_MONTHS';end if;
  else cs:=date_trunc('day',now());ce:=cs+interval '1 day';end if;
 end if;
 select * into c from public.lj_usage_cycles where user_id=p_user_id and plan_key=p and billing_period=b and cycle_start<=now() and cycle_end>now() order by cycle_end desc limit 1 for update;
 if not found then insert into public.lj_usage_cycles(user_id,plan_key,billing_period,cycle_start,cycle_end,text_limit,image_limit,voice_seconds_limit,refills_total,refill_on_request) values(p_user_id,p,b,cs,ce,tl,il,vl,rf,rq) on conflict(user_id,cycle_start) do update set plan_key=excluded.plan_key,billing_period=excluded.billing_period,cycle_end=excluded.cycle_end,text_limit=excluded.text_limit,image_limit=excluded.image_limit,voice_seconds_limit=excluded.voice_seconds_limit,refills_total=excluded.refills_total,refill_on_request=excluded.refill_on_request,updated_at=now() returning * into c;end if;return c;
end$$;

create or replace function public.consume_lj_usage(p_user_id uuid,p_kind text,p_amount integer default 1) returns table(allowed boolean,plan_key text,text_remaining integer,image_remaining integer,voice_seconds_remaining integer,refills_remaining integer) language plpgsql security definer set search_path=public as $$
declare c public.lj_usage_cycles%rowtype;
begin c:=public.ensure_lj_usage_cycle(p_user_id);p_amount:=greatest(1,p_amount);
 if upper(p_kind)='TEXT' then allowed:=c.text_limit is null or c.text_used+p_amount<=c.text_limit;if allowed then update public.lj_usage_cycles set text_used=text_used+p_amount,updated_at=now() where user_id=p_user_id and cycle_start=c.cycle_start returning * into c;end if;
 elsif upper(p_kind)='IMAGE' then allowed:=c.image_limit is null or c.image_used+p_amount<=c.image_limit;if allowed then update public.lj_usage_cycles set image_used=image_used+p_amount,updated_at=now() where user_id=p_user_id and cycle_start=c.cycle_start returning * into c;end if;
 elsif upper(p_kind)='VOICE' then allowed:=c.voice_seconds_limit is null or c.voice_seconds_used+p_amount<=c.voice_seconds_limit;if allowed then update public.lj_usage_cycles set voice_seconds_used=voice_seconds_used+p_amount,updated_at=now() where user_id=p_user_id and cycle_start=c.cycle_start returning * into c;end if;else allowed:=false;end if;
 plan_key:=c.plan_key;text_remaining:=case when c.text_limit is null then null else greatest(0,c.text_limit-c.text_used) end;image_remaining:=case when c.image_limit is null then null else greatest(0,c.image_limit-c.image_used) end;voice_seconds_remaining:=case when c.voice_seconds_limit is null then null else greatest(0,c.voice_seconds_limit-c.voice_seconds_used) end;refills_remaining:=greatest(0,c.refills_total-c.refills_used);return next;end$$;

create or replace function public.use_lj_usage_refill(p_user_id uuid) returns table(used boolean,refills_remaining integer) language plpgsql security definer set search_path=public as $$declare c public.lj_usage_cycles%rowtype;begin c:=public.ensure_lj_usage_cycle(p_user_id);if c.refills_used>=c.refills_total then used:=false;refills_remaining:=0;return next;return;end if;update public.lj_usage_cycles set text_used=0,image_used=0,refills_used=refills_used+1,updated_at=now() where user_id=p_user_id and cycle_start=c.cycle_start returning * into c;insert into public.lj_usage_refill_events(user_id,cycle_start,refill_number,used_at) values(p_user_id,c.cycle_start,c.refills_used,now());used:=true;refills_remaining:=greatest(0,c.refills_total-c.refills_used);return next;end$$;

create or replace function public.grant_lj_usage_refill(p_user_id uuid) returns table(granted boolean,refills_total integer,refills_remaining integer) language plpgsql security definer set search_path=public as $$declare c public.lj_usage_cycles%rowtype;begin c:=public.ensure_lj_usage_cycle(p_user_id);if c.plan_key<>'VIP' or c.billing_period<>'3_MONTHS' then granted:=false;refills_total:=c.refills_total;refills_remaining:=greatest(0,c.refills_total-c.refills_used);return next;return;end if;update public.lj_usage_cycles set refills_total=refills_total+1,updated_at=now() where user_id=p_user_id and cycle_start=c.cycle_start returning * into c;granted:=true;refills_total:=c.refills_total;refills_remaining:=greatest(0,c.refills_total-c.refills_used);return next;end$$;

alter table public.lj_subscriptions enable row level security;alter table public.lj_usage_cycles enable row level security;alter table public.lj_usage_refill_events enable row level security;alter table public.lj_user_preferences enable row level security;alter table public.lj_conversations enable row level security;alter table public.lj_conversation_messages enable row level security;alter table public.lj_voice_sessions enable row level security;alter table public.billing_webhook_events enable row level security;
revoke all on public.lj_subscriptions,public.lj_usage_cycles,public.lj_usage_refill_events,public.lj_user_preferences,public.lj_conversations,public.lj_conversation_messages,public.lj_voice_sessions,public.billing_webhook_events from anon,authenticated;
grant all on public.lj_subscriptions,public.lj_usage_cycles,public.lj_usage_refill_events,public.lj_user_preferences,public.lj_conversations,public.lj_conversation_messages,public.lj_voice_sessions,public.billing_webhook_events to service_role;
revoke all on sequence public.lj_usage_refill_events_id_seq from anon,authenticated;grant usage,select on sequence public.lj_usage_refill_events_id_seq to service_role;
revoke all on function public.ensure_lj_usage_cycle(uuid),public.consume_lj_usage(uuid,text,integer),public.use_lj_usage_refill(uuid),public.grant_lj_usage_refill(uuid) from public,anon,authenticated;grant execute on function public.ensure_lj_usage_cycle(uuid),public.consume_lj_usage(uuid,text,integer),public.use_lj_usage_refill(uuid),public.grant_lj_usage_refill(uuid) to service_role;
commit;
